import type { AgentRegistryEntry } from './types'

export const agentRegistry: AgentRegistryEntry[] = [
  {
    id: 'court-clerk',
    name: 'Mnemon',
    seat: 'court-clerk',
    description: 'Court Clerk. Opens cases, timestamps the hearing, maintains the court record, and prepares hashes for Arc.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.02,
    permissions: ['read_case', 'read_public_evidence', 'request_payment'],
    inputSchema: 'court-case-v1',
    outputSchema: 'court-record-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'evidence-clerk',
    name: 'Kleio',
    seat: 'evidence-clerk',
    description: 'Evidence Clerk. Files exhibits, organizes source trails, and prepares evidence packets for counsel.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.03,
    permissions: ['read_case', 'read_public_evidence', 'submit_evidence', 'request_payment'],
    inputSchema: 'court-case-v1',
    outputSchema: 'evidence-packet-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'pythia-prediction-witness',
    name: 'Pythia',
    seat: 'expert-witness',
    description: 'Prediction Witness. Testifies on prediction-market odds, implied probability, and mispricing.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.04,
    permissions: ['read_case', 'read_public_evidence', 'submit_testimony', 'request_payment'],
    inputSchema: 'court-case-v1',
    outputSchema: 'witness-testimony-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'hermes-news-witness',
    name: 'Hermes',
    seat: 'expert-witness',
    description: 'News Witness. Testifies on headline flow, source quality, and information freshness.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.03,
    permissions: ['read_case', 'read_public_evidence', 'submit_testimony', 'request_payment'],
    inputSchema: 'court-case-v1',
    outputSchema: 'witness-testimony-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'argos-onchain-witness',
    name: 'Argos',
    seat: 'expert-witness',
    description: 'Onchain Witness. Testifies on wallet flow, exchange movement, and onchain behavior.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.04,
    permissions: ['read_case', 'read_public_evidence', 'submit_testimony', 'request_payment'],
    inputSchema: 'court-case-v1',
    outputSchema: 'witness-testimony-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'bull-counsel',
    name: 'Solon',
    seat: 'bull-counsel',
    description: 'Bull Counsel. Argues the upside or yes case and proposes the strongest positive interpretation.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.05,
    permissions: ['read_case', 'read_public_evidence', 'submit_argument', 'request_payment'],
    inputSchema: 'evidence-packet-v1',
    outputSchema: 'counsel-argument-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'bear-counsel',
    name: 'Draco',
    seat: 'bear-counsel',
    description: 'Bear Counsel. Argues the downside or no case and challenges weak assumptions.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.05,
    permissions: ['read_case', 'read_public_evidence', 'submit_argument', 'request_payment'],
    inputSchema: 'evidence-packet-v1',
    outputSchema: 'counsel-argument-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'risk-bailiff',
    name: 'Phylax',
    seat: 'risk-bailiff',
    description: 'Risk Bailiff. Checks confidence, evidence quality, liquidity context, and uncertainty before verdict.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.02,
    permissions: ['read_case', 'read_public_evidence', 'submit_risk_review', 'request_payment'],
    inputSchema: 'counsel-argument-v1',
    outputSchema: 'risk-review-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'dikast-momentum',
    name: 'Kallias',
    seat: 'juror',
    description: 'Dikast Juror. Evaluates whether momentum and fresh signals support a clearer verdict.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.01,
    permissions: ['read_case', 'read_public_evidence', 'submit_jury_vote', 'request_payment'],
    inputSchema: 'hearing-brief-v1',
    outputSchema: 'jury-vote-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'dikast-skeptic',
    name: 'Thraso',
    seat: 'juror',
    description: 'Dikast Juror. Challenges overconfidence and votes from a skeptical market lens.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.01,
    permissions: ['read_case', 'read_public_evidence', 'submit_jury_vote', 'request_payment'],
    inputSchema: 'hearing-brief-v1',
    outputSchema: 'jury-vote-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'dikast-risk',
    name: 'Sophon',
    seat: 'juror',
    description: 'Dikast Juror. Votes from an uncertainty, source-quality, and evidence-risk perspective.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.01,
    permissions: ['read_case', 'read_public_evidence', 'submit_jury_vote', 'request_payment'],
    inputSchema: 'hearing-brief-v1',
    outputSchema: 'jury-vote-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'head-judge',
    name: 'Archon',
    seat: 'head-judge',
    description: 'Head Judge. Weighs evidence, counsel arguments, dissent, and risk constraints to issue the verdict.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0,
    permissions: ['read_case', 'read_public_evidence', 'submit_verdict_recommendation'],
    inputSchema: 'hearing-brief-v1',
    outputSchema: 'verdict-v1',
    enabled: true,
    version: '0.1.0',
  },
  {
    id: 'settlement-clerk',
    name: 'Nomisma',
    seat: 'settlement-clerk',
    description: 'Settlement Clerk. Calculates agent payouts, protocol fees, and Arc court receipt events.',
    owner: 'protocol',
    mode: 'local',
    priceUsd: 0.02,
    permissions: ['read_case', 'request_payment'],
    inputSchema: 'verdict-v1',
    outputSchema: 'settlement-plan-v1',
    enabled: true,
    version: '0.1.0',
  },
]

export function getEnabledAgents() {
  return agentRegistry.filter((agent) => agent.enabled)
}
